### PR TITLE
[159, 160, 167] Bug fixes

### PR DESCRIPTION
**Pull request by SaidganiUsm**
Where
[NL-160 Update search placeholder text](https://jjbcapital.atlassian.net/browse/NL-160)
[NL-159 Make tabs Wishlist and Dashboard visible only for logged in users](https://jjbcapital.atlassian.net/browse/NL-159)
[NL-167 Fix rating stars on seller dashboard](https://jjbcapital.atlassian.net/browse/NL-167)

What
Bug fixes

Affected Area
Auctionify.API.ClientApp

PR Checklist
Build

 Build Succeeded
Unit Tests

[x] All 84 Tests Passed, 0 Ignored, 0 Failed

### CODE REVIEW

**Comment by khasanrashidov** [comment]
1. remove that black border from modal component, when I click there is black border around it.

image

2. Here I would suggest using mat-flat-button for log out button (instead of raised one, the cancel button looks great, no issues):

image

3. When I a click log out in home page.. the home page doesn't refresh, I still see add to watchlist buttons over the lots, it should refresh (as it was before):

image

4. Actually, I would remove the search bar as well, because the search doesn't work when user is logget out (i.e. not authorized)... And in that case the header would look better and aesthetic, I think. Think about it and consider using it.

image

**Comment by khasanrashidov** [comment]
In profile (of seller and buyer), there is logout button. The message appearing there and in other logout button (opening other logout modal component) is different, and the one in profile page has autofocus on and logout button there has raised button style, remove it. Or better use the you already have in the header or navbar of seller:

image

image

The one in header or navbar:

image

**Review by khasanrashidov — CHANGES_REQUESTED** [review]
Check my thread where I am addressing changes, fix them please)

**Review by otash8110 — APPROVED** [review]

**Review by khasanrashidov — APPROVED** [review]
Great, resolved all pointed issues!)

**Review by TsvirkoNikita — APPROVED** [review]

**Pull request merged**
